# Generated by Django 3.2 on 2021-05-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiretubers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiretuber',
            name='tuber_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hiretuber',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
