# Generated by Django 3.2 on 2021-05-25 20:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiretubers', '0002_auto_20210522_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiretuber',
            name='messages',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
