# Generated by Django 3.2.3 on 2021-05-29 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('youtubers', '0004_youtuber_emailid'),
        ('hiretubers', '0005_alter_hiretuber_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiretuber',
            name='tuber_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='youtubers.youtuber'),
        ),
        migrations.AlterField(
            model_name='hiretuber',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
