# Generated by Django 3.2.3 on 2021-05-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiretubers', '0006_auto_20210529_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiretuber',
            name='tuber_id',
            field=models.IntegerField(),
        ),
    ]
