# Generated by Django 3.2.3 on 2021-05-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiretubers', '0007_alter_hiretuber_tuber_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiretuber',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
