# Generated by Django 3.2 on 2021-05-23 14:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('facebook', models.CharField(max_length=255)),
                ('instagram', models.CharField(max_length=255)),
                ('twitter', models.CharField(max_length=255)),
                ('youtube', models.CharField(max_length=255)),
                ('about_photo', models.ImageField(default='', upload_to='media/about/%Y/%M/')),
                ('about_project', ckeditor.fields.RichTextField(default='')),
            ],
        ),
    ]
