# Generated by Django 3.2 on 2021-05-23 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_form',
            old_name='user_contactno',
            new_name='contactno',
        ),
        migrations.RenameField(
            model_name='contact_form',
            old_name='user_emailid',
            new_name='emailid',
        ),
        migrations.RenameField(
            model_name='contact_form',
            old_name='user_name',
            new_name='name',
        ),
    ]
