# Generated by Django 3.2 on 2021-05-23 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20210523_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_form',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
