# Generated by Django 3.2.3 on 2021-05-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_contact_form_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_form',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
