# Generated by Django 3.1.7 on 2021-02-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='photo',
            field=models.ImageField(default='', upload_to='media/slider/%Y/'),
        ),
    ]
