# Generated by Django 3.1.7 on 2021-02-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_auto_20210226_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='links',
            field=models.CharField(default='', max_length=255),
        ),
    ]
