# Generated by Django 3.1.7 on 2021-02-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_slider_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=80)),
                ('insta_link', models.CharField(max_length=255)),
                ('linkedin_link', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='media/team/%Y/%M/%D/')),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
