# Generated by Django 3.2 on 2021-05-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_team_youtube_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(max_length=255)),
                ('phone_no', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('facebook', models.CharField(max_length=255)),
                ('instagram', models.CharField(max_length=255)),
                ('twitter', models.CharField(max_length=255)),
                ('youtube', models.CharField(max_length=255)),
            ],
        ),
    ]
