# Generated by Django 3.2 on 2021-05-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0006_contact_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_info',
            name='phone_no',
            field=models.CharField(max_length=255),
        ),
    ]
