# Generated by Django 3.2 on 2021-05-23 10:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0007_alter_contact_info_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_info',
            name='about_photo',
            field=models.ImageField(default='', upload_to='media/about/%Y/%M/'),
        ),
        migrations.AddField(
            model_name='contact_info',
            name='about_project',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
