# Generated by Django 3.2 on 2021-05-23 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0008_auto_20210523_1624'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact_info',
        ),
    ]
